2024-12-04 21:48:39,194 INFO: Application startup [in /Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/__init__.py:62]
2024-12-04 21:48:45,987 ERROR: Exception on /login [GET] [in /Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/main/routes.py", line 41, in login
    return render_template('login.html')
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/base.html", line 213, in top-level template code
    {% block page_content %}{% endblock %}
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/login.html", line 31, in block 'page_content'
    {{ form.hidden_tag() }}
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2024-12-04 21:48:48,185 ERROR: Exception on /login [GET] [in /Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/main/routes.py", line 41, in login
    return render_template('login.html')
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/base.html", line 213, in top-level template code
    {% block page_content %}{% endblock %}
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/login.html", line 31, in block 'page_content'
    {{ form.hidden_tag() }}
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2024-12-04 21:48:48,918 ERROR: Exception on /login [GET] [in /Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/main/routes.py", line 41, in login
    return render_template('login.html')
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/base.html", line 213, in top-level template code
    {% block page_content %}{% endblock %}
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/login.html", line 31, in block 'page_content'
    {{ form.hidden_tag() }}
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2024-12-04 21:51:34,190 INFO: Application startup [in /Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/__init__.py:65]
2024-12-04 21:51:34,432 INFO: Application startup [in /Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/__init__.py:65]
2024-12-04 21:51:34,664 INFO: Application startup [in /Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/__init__.py:65]
